events {}
http {
    server {
        listen 80;

        location / {
            default_type text/html;
            return 200 "<html><head><title>Nginx Dummy Site</title><style>body{background:#0f172a;color:#f8fafc;font-family:sans-serif;text-align:center;padding:50px;line-height:1.6;}</style></head><body><h1>Welcome to the Nginx Dummy Website!</h1><p style='font-size: 1.2rem; max-width: 600px; margin: 0 auto;'>Yeh ek dummy website hai. Agar aap dashboard se Nginx crash karoge, toh yeh website crash (down) ho jayegi. Uske baad Ansible isko auto-recover karega aur yeh wapas live ho jayegi.</p></body></html>";
        }
    }
}
